<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Pace</AssemblyName>
    <RootNamespace>Usage</RootNamespace>
    <Product>Pace</Product>
    <Title>Pace</Title>
    <Version>0.2.0</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\Icons\pace.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\Fonts\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="Assets\Icons\*.png" />
    <EmbeddedResource Include="Assets\Icons\pace.ico" />
    <EmbeddedResource Include="scripts\Install-Update.ps1" />
    <Content Include="Assets\Icons\*.svg;Assets\Icons\*.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
